# .github/workflows/build.yml
name: Java Mobile App Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java environment
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # Puedes usar 'temurin' o 'zulu' según tu preferencia
        java-version: '17'   # Cambia a la versión que usa tu proyecto

    # Step 3: Cache Gradle dependencies
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Step 4: Build the project
    - name: Build the app
      run: ./gradlew build

    # Step 5: Run unit tests
    - name: Run tests
      run: ./gradlew test
